# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GitHub Pages Demo Test 1
email: sakamoto.gsyc.3s@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: msakamoto_sf
github_username: msakamoto-sf

# Build settings
markdown: GFM
theme: minima
plugins:
  - jekyll-feed
# github サイト上でTOPに表示されるREADME.mdと、Webサイトのデフォルトで表示される index コンテンツは分けておきたい。
# README.md にはサイトをビルドするときの手順や編集の注意点などを書いておき、
# index.{html|md} にサイトの内容を表示するようにする。
# jekyll-readme-index は標準で組み込まれるため、index.md を意図的に残しておき、README.md と分ける。


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# foo/bar/ 以下をmarkdownとして処理させずに、静的なファイルとして単にコピーさせる方法が分からない。
# https://github.com/jekyll/jekyll/issues/77
# exclude で除外する方法も紹介されているが、これではファイルコピー自体が発生しないので、
# 公開用ディレクトリに foo/bar/ がコピーされない。
# そうではなく、 .md や .html も含めて単にファイルとしてコピーしたいだけなのだが・・・。
# -> 上記 issue での一連の流れを見るに、jekyllのビルドシステムそのものをカスタマイズするとか、
# jekyll の外部でビルドシステムを組み上げるしかなさそう。
# 試しに以下のような exclude 設定をしてみたが、foo/ は _site にコピーされないままとなった。
#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules
#  - vendor/
#  - foo/
